# -*- coding: utf-8 -*-
"""reports.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lXb-Hjquz5yk3TSM1_mur-0Vw7jZ1dt

**COVID-19 State-wise Reporting Module**

**Author:** AKANKSHA MISHRA

**Purpose:** Generate actionable state-wise COVID-19 reports with insights for policymakers
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

#Configurable Parameters
dataset_path = "India_COVID19_Statewise_TimeSeries_Analytics_2021.csv"
output_dir = "reports"
top_n_states = 3  # show top 3 states for key metrics

"""**1. Load Dataset with Error Handling**"""

try:
    df = pd.read_csv(dataset_path)
except FileNotFoundError:
    print(f"Error: Dataset not found at {dataset_path}")
    print(" Please upload the dataset to the current folder or update the path.")
    exit(1)

from google.colab import files
uploaded = files.upload()

dataset_path = "India_COVID19_Statewise_TimeSeries_Analytics_2021.csv"
df = pd.read_csv(dataset_path)

df.head(2)

# Keep only the exact columns in dataset
columns_needed = [
    'Date','State_UT','Population','New_Cases','New_Deaths',
    'New_Recoveries','Total_Cases','Total_Deaths','Total_Recoveries','Active_Cases'
]
df = df[columns_needed]

# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'])

"""**2. Prepare Output Folder**"""

os.makedirs(output_dir, exist_ok=True)

"""**3. Aggregate Summary Metrics per State/UT**"""

summary = df.groupby('State_UT').agg(
    Population=('Population', 'max'),
    Total_Cases=('Total_Cases', 'max'),
    Total_Deaths=('Total_Deaths', 'max'),
    Total_Recoveries=('Total_Recoveries', 'max'),
    Active_Cases=('Active_Cases', 'max'),
    Max_New_Cases=('New_Cases', 'max'),
    Max_New_Deaths=('New_Deaths', 'max'),
    Max_New_Recoveries=('New_Recoveries', 'max')
).reset_index()

# Save summary CSV
summary_path = f"{output_dir}/statewise_summary.csv"
summary.to_csv(summary_path, index=False)
print(f"State-wise summary saved to {summary_path}")

"""**4. Top-Risk State Insights**"""

top_cases = summary.sort_values('Total_Cases', ascending=False).head(top_n_states)
top_deaths = summary.sort_values('Total_Deaths', ascending=False).head(top_n_states)
top_active = summary.sort_values('Active_Cases', ascending=False).head(top_n_states)

print("\n Top States by Total Cases:")
print(top_cases[['State_UT','Total_Cases','Active_Cases','Total_Deaths']].to_string(index=False))

print("\n Top States by Total Deaths:")
print(top_deaths[['State_UT','Total_Deaths','Total_Cases','Active_Cases']].to_string(index=False))

print("\n Top States by Active Cases:")
print(top_active[['State_UT','Active_Cases','Total_Cases','Total_Deaths']].to_string(index=False))

"""**5. Generate Visual Reports per State**"""

states = df['State_UT'].unique()

for state in states:
    state_df = df[df['State_UT'] == state]

    plt.figure(figsize=(6,5))
    plt.plot(state_df['Date'], state_df['Total_Cases'], label='Total Cases', color='blue')
    plt.plot(state_df['Date'], state_df['Active_Cases'], label='Active Cases', color='orange')
    plt.plot(state_df['Date'], state_df['Total_Recoveries'], label='Total Recoveries', color='green')
    plt.plot(state_df['Date'], state_df['Total_Deaths'], label='Total Deaths', color='red')

"""**6. Add forecast data integration**"""

# forecast_df = pd.read_csv(f"forecasts/forecast_{state.replace(' ','_')}.csv")
    # plt.plot(forecast_df['ds'], forecast_df['yhat'], label='Forecasted Total Cases', linestyle='--')

plt.title(f"COVID-19 Key Metrics Over Time - {state}")
plt.xlabel("Date")
plt.ylabel("Count")
plt.legend()
plt.tight_layout()

plt.savefig(f"{output_dir}/report_{state.replace(' ', '_')}.png")
plt.close()

print(f"Report generated for {state}")

print("\n All state-wise reports completed successfully!")